In [15]:
import requests
import tabula.io as tb
import pandas as pd
import pdfplumber
import re

In [3]:
url = "https://nuc.edu.ng/wp-content/uploads/2015/09/Sciences%20Draft%20BMAS.pdf"
r = requests.get(url)
with open("Sciences_BMAS.pdf", "wb") as f:
    f.write(r.content)

dfs = tb.read_pdf(
    "Sciences_BMAS.pdf", 
    pages="all", 
    multiple_tables=True,
    encoding="ISO-8859-1",
    silent=True
)
courses = pd.concat(dfs, ignore_index=True)
courses.head()

Failed to import jpype dependencies. Fallback to subprocess.
No module named 'jpype'

,1.1 Programmes and Degrees........................................................................................................... 1,1.5.1 Course System ....................................................................................................................................... 3,2.1.1,Common Basic Science Courses. ........................................................................................................ 13,3.8.8 Course Synopses: ................................................................................................................................. 91,3.9.6 Resource Requirement for Teaching and Learning ........................................................................... 101,3.14.7 Course Synopses: .......................................................................................................................... 156,3.19.21,Course Structure of Chemical/Petroleum Technology Techniques .............................................. 265,4.5,...,(1),4.,Ph Meter,1.,Pyscrometer,5.,Pollution,(I),14.,Sunshine Recorder
0,1.2 Philosophy and Objectives ...................,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.3 Basic Admission Requirements and Expected ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.4 Minimum Duration ............................,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1.5.2 Standard Terminologies ....................,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,1.5.3 Grading of Courses ........................,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
courses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2368 entries, 0 to 2367
Columns: 327 entries, 1.1 Programmes and Degrees........................................................................................................... 1 to Sunshine Recorder
dtypes: float64(111), object(216)
memory usage: 5.9+ MB

In [5]:
clean_df = courses.dropna(axis=1, how='all')
print("Remaining columns:", clean_df.shape)
clean_df.head()

Remaining columns: (2368, 231)

,1.1 Programmes and Degrees........................................................................................................... 1,1.5.1 Course System ....................................................................................................................................... 3,2.1.1,Common Basic Science Courses. ........................................................................................................ 13,3.8.8 Course Synopses: ................................................................................................................................. 91,3.9.6 Resource Requirement for Teaching and Learning ........................................................................... 101,3.14.7 Course Synopses: .......................................................................................................................... 156,3.19.21,Course Structure of Chemical/Petroleum Technology Techniques .............................................. 265,4.5,...,(1),4.,Ph Meter,1.,Pyscrometer,5.,Pollution,(I),14.,Sunshine Recorder
0,1.2 Philosophy and Objectives ...................,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.3 Basic Admission Requirements and Expected ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.4 Minimum Duration ............................,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1.5.2 Standard Terminologies ....................,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,1.5.3 Grading of Courses ........................,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2368 entries, 0 to 2367
Columns: 231 entries, 1.1 Programmes and Degrees........................................................................................................... 1 to Sunshine Recorder
dtypes: float64(15), object(216)
memory usage: 4.2+ MB

In [7]:
flat_data = []

for _, row in clean_df.iterrows():
    non_nulls = row.dropna().tolist()
    if non_nulls:
        flat_data.append(non_nulls)

flat_df = pd.DataFrame(flat_data)
print(flat_df.shape)
flat_df.head()

(2339, 12)

,0,1,2,3,4,5,6,7,8,9,10,11
0,1.2 Philosophy and Objectives ...................,None,None,None,None,None,None,None,None,None,None,None
1,1.3 Basic Admission Requirements and Expected ...,None,None,None,None,None,None,None,None,None,None,None
2,1.4 Minimum Duration ............................,None,None,None,None,None,None,None,None,None,None,None
3,1.5.2 Standard Terminologies ....................,None,None,None,None,None,None,None,None,None,None,None
4,1.5.3 Grading of Courses ........................,None,None,None,None,None,None,None,None,None,None,None

In [9]:
flat_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2339 entries, 0 to 2338
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2339 non-null   object
 1   1       2057 non-null   object
 2   2       1863 non-null   object
 3   3       1748 non-null   object
 4   4       1660 non-null   object
 5   5       1218 non-null   object
 6   6       17 non-null     object
 7   7       6 non-null      object
 8   8       5 non-null      object
 9   9       2 non-null      object
 10  10      2 non-null      object
 11  11      2 non-null      object
dtypes: object(12)
memory usage: 219.4+ KB

In [12]:
flat_df.to_csv("cleaned_bmas_sections.csv", index=False)

In [18]:
# with pdfplumber.open("Sciences_BMAS.pdf") as pdf:
#     for i, page in enumerate(pdf.pages[30:50]):  # First 5 pages for now
#         text = page.extract_text()
#         print(f"\n========== Page {i+1} ==========\n")
#         print(text[:1000])
with pdfplumber.open("Sciences_BMAS.pdf") as pdf:
    for i in range(30, 50):  # Try a wider range
        text = pdf.pages[i].extract_text()
        print(f"\n========= Page {i+1} =========")
        for line in text.split("\n"):
            if re.search(r"[A-Z]{3,4}\s?\d{3}", line):  # Looks like course code
                print(line)

========= Page 31 =========

========= Page 32 =========
BIO 101 General Biology I 3 R 45 -
BIO 102 General Biology II 3 R 45 -
BIO 107 General Biology Practical I 1 R - 45
BIO 108 General Biology Practical II 1 R - 45
CHM 101 General Chemistry I 3 R 45 -
CHM 102 General Chemistry II 3 R 45 -
CHM 107 General Chemistry Practical I 1 R - 45
CHM 108 General Chemistry Practical II 1 R - 45
CSC 101 Introduction to Computer Science 3 R 30 45
GST 111 Communication in English I 2 C 30 -
GST 112 Logic, Philosophy & Human Existence 2 E 30 -
GST 113 Nigerian Peoples and Culture 2 R 30 -
GST 121 Use of Library, Study skills and ICT 2 R 30 -
MTH 101 Elementary Mathematics I 3 R 45 -

========= Page 33 =========
MTH 102 Elementary Mathematics II 3 R 45 -
PHY 101 General Physics I 3 R 45 -
PHY 102 General Physics II 3 R 45 -
PHY 107 General Physics Practical I 1 R - 45
PHY 108 General Physics Practical II 1 R - 45
BCH 201 General Biochemistry I 3 C 45 -
BCH 202 General Biochemistry II 3 C 45 -
BCH 203 General Biochemistry Practical I 1 C - 45
BCH 299 Industrial Attachment I (12 Weeks) 3 C
BIO 201 Genetics I 2 R 30 -
BIO 204 Biological Techniques 2 R 15 45
CHM 210 Physical Chemistry I 3 C 30 45
CHM 211 Organic Chemistry I 3 C 30 45
CHM 212 Inorganic Chemistry I 3 R 30 45
GST 122 Communication in English II 2 C 30 -
GST 125 Contemporary Health Issues 2 R 30 -
GST 211 Environment and Sustainable 2 R 30 -
GST 223 Introduction to Entrepreneurship 2 R 30 -
MCB 221 General Microbiology 3 R 30 45
STA 201 Statistics for Agriculture & 4 R 60 -

========= Page 34 =========
BCH 301 Introductory Enzymology 3 C 45 -
BCH 302 Chemistry and Metabolism of 2 R 30 -
BCH 303 Chemistry and Metabolism of Lipids 2 R 30 -
BCH 304 Chemistry & Metabolism of amino 2 C 30 -
BCH 305 Chemistry & Metabolism of Nucleic 2 C 30 -
BCH 306 Analytical Methods in Biochemistry 3 C 30 45
BCH 307 Membrane Biochemistry 1 R 15 -
BCH 308 Food & Nutritional Biochemistry 2 R 30 -
BCH 310 Bioenergetics 1 R 15 -
BCH 311 General Biochemistry Practical II 2 C - 90
BCH 312 Principles of Endocrinology 2 R 30 -
BCH 313 Principles of Immunology 2 R 30 -
BCH 314 Toxicology I 2 R 30 -
BCH 399 Industrial Attachment II (12 weeks) 3 C
CHM 301 Physical Chemistry II 3 R 30 45
CHM 303 Organic Chemistry II 3 R 30 45
GST 222 Peace Studies and Conflict Resolution 2 R 30 -
GST 224 Leadership Skills 2 R 30 -
GST 311 Entrepreneurship 2 R 30 -
BCH 401 Enzymology 2 C 30 -
BCH 402 Biosynthesis of Macromolecules 1 R 15 -
BCH 403 Tissue Biochemistry 1 E 15 -
BCH 404 Bioinorganic Chemistry 1 E 15 -
BCH 405 Molecular Biology 3 C 45 -
BCH 406 Metabolic Regulations 2 R 30 -
BCH 407 Plant Biochemistry 2 E 30 -
BCH 408 Biochemical Reasoning 1 R 15 -
BCH 409 Special Topics/Seminar in 2 R 30 -
BCH 410 Advanced Biochemical Methods 2 R - 90
BCH 411 Research Project 6 C - 270
BCH 412 Industrial Biochemistry 3 R 45 -
BCH 413 Pharmacological Biochemistry 2 R 30 -
BCH 414 Endocrinology 2 R 30 -

========= Page 35 =========
BCH 415 Forensic Biochemistry 3 R 45 -
BCH 416 Molecular Aspects of Immunology 2 R 30 -
BCH 417 Toxicology II 2 R 30 -
BCH 201: General Biochemistry I (3 Units: LH 45)
BCH 202: General Biochemistry II (3 Units: LH 45)
BCH 203: General Biochemistry Practical I (1 Unit: PH 45)
Laboratory experiments designed to reflect the topics covered in BCH 201 and BCH 202.
BCH 299: Industrial Attachment I (3 Units)
BCH 301: Enzymology (3 Units: LH 45)
BCH 302: Chemistry and Metabolism of Carbohydrates (2 Units: LH 30)

========= Page 36 =========
BCH 303: Chemistry and Metabolism of Lipids (2 Units: LH 30)
BCH 304: Chemistry and Metabolism of Amino Acids & Proteins (2 Units: LH 30)
BCH 305: Chemistry and Metabolism of Nucleic Acids (2 Units: LH 30)
BCH 306: Analytical Methods in Biochemistry (3 Units: LH 30; PH 45)
BCH 307: Membrane Biochemistry (1 Unit: LH 15)

========= Page 37 =========
BCH 308: Food and Nutrition Biochemistry (2 Units: LH 30)
BCH 310: Bioenergetics (1 Unit: LH 15)
BCH 311: General BRiochemistry Practical II (2 Units: PH 90)
BCH 312: Principles of Endocrinology (2 Units: LH 30)
BCH 313: Principles of Immunology (2 Units: LH 30)

========= Page 38 =========
BCH 314: Toxicology I (2 Units: LH 30)
BCH 399: Industrial Attachment II (3 Units)
BCH 401: Enzymology (2 Units: LH 30)
BCH 402: Biosynthesis of Macromolecules (1 Unit: LH 15)
BCH 403: Tissue Biochemistry (1 Unit: LH 15)
BCH 404: Bioinorganic Chemistry (1 Unit: LH 15)
BCH 405: Molecular Biology (3 Units: LH 45)
BCH 406: Metabolic Regulations (2 Units: LH 30)

========= Page 39 =========
BCH 407: Plant Biochemistry (2 Units: LH 30)
BCH 408: Biochemical Reasoning (1 Unit: LH 15)
BCH 409: Special Topics/Seminar in Biochemistry (2 Units: LH 30)
BCH 410: Advanced Biochemical Methods (Practical) (2 Units: PH 90)
BCH 411: Research Projects (6 Units: PH 270)
BCH 412: Industrial Biochemistry (3 Units: LH 45)
BCH 413: Pharmacological Biochemistry (2 Units: LH 30)

========= Page 40 =========
BCH 414: Endocrinology (2 Units: LH 30)
BCH 415: Forensic Biochemistry (3 Units: LH 45)
BCH 416: Molecular Aspects
BCH 417: Toxicology II (2 Units: LH 30)

========= Page 41 =========

========= Page 42 =========
BIO 101 GeRneral Biology I 3 C 45 -
BIO 102 General Biology II 3 C 45 -
BIO 107 General Biology Practical I 1 C - 45
BIO 108 General Biology Practical II 1 C - 45
CHM 101D General Chemistry I 3 R 45 -
CHM 102 General Chemistry II 3 R 45 -
CHM 107 General Chemistry Practical I 1 R - 45
CHM 108 General Chemistry Practical II 1 R - 45
CSC 101 Introduction to Computer Science 3 R 30 45
GST 111 Communication in English I 2 C 30 -
GST 112 Logic, Philosophy & Human Existence 2 E 30 -
GST 113 Nigerian Peoples and Culture 2 R 30 -
GST 121 Use of Library, Study Skills & ICT 2 R 30 -
MTH 101 Elementary Mathematics I 3 R 45 -
PHY 101 General Physics I 3 R 45 -
PHY 102 General Physics II 3 R 45 -
PHY 107 General Physics Practical I 1 R - 45
PHY 108 General Physics Practical II 1 R - 45
STA 111 Descriptive Statistics 4 R 60 -

========= Page 43 =========
BIO 201 Genetics I 2 C 30 -
BIO 202 Introductory Ecology 2 C 15 45
BIO 203 General Physiology I 2 C 30 -
BIO 204 Biological Techniques 2 C 15 45
BIO 205 Introductory Developmental/Cell 3 R 30 45
BIO 299 Industrial Attachment I (12 weeks) 3 C - -
BOT 202 Seedless Plants 2 R 30 -
BOT 203 Seed Plants 2 E 30 -
CHM 211 Organic Chemistry I 3 R 30 45
CHM 213 Analytical Chemistry I 3 E 30 45
GST 122 Communication in English II T2 C 30 -
GST 125 Contemporary Health Issues 2 R 30 -
GST 211 Environment and Sustainable 2 R 30 -
GST 223 Introduction to Entrepreneurship 2 R 30 -
MCB 221 General Microbiology 3 E 30 45
STA 201 Statistics for Agriculture & Biological 4 R 60 -
ZOO 211 Invertebrate Zoology 3 R 30 45
ZOO 212 Chordate Zoology 3 E 30 45
BCH 201D General Biochemistry I 3 R 45 -
BCH 202 General Biochemistry II 3 R 45 -
BIO 301 Genetics II 3 C 30 45
BIO 302 Field Course I 1 R - 45
BIO 303 General Cytology 3 R 30 45
BIO 304 General Ecology 3 R 30 45
BIO 305 Molecular Biology 3 R 45 -
BIO 306 General Physiology II 3 R 30 45
BIO 308 Evolution 2 E 30 -
BIO 309 Introductory Nematology 2 E 30 -
BIO 399 Industrial Attachment II (12 weeks) 3 C - -
GST 222 Peace Studies and Conflict Resolution 2 R 30 -
GST 224 Leadership Skills 2 R 30 -
GST 311 Entrepreneurship 2 R 30 -
MCB 307 Immunology 3 E 30 45
MCB 309 Food Microbiology 2 E 15 45
MCB 324 Microbial Ecology 3 E 30 45
MCB 326 Introductory Virology 3 E 30 45

========= Page 44 =========
BIO 401 Population Genetics 3 C 45 -
BIO 402 Cytogenetics of Plants 3 C 30 45
BIO 403 Soil Ecology 3 C 45 -
BIO 404 Systematic Biology 3 C 45 -
BIO 405 Developmental Biology 3 C 30 45
BIO 406 Marine Biology 3 E 30 45
BIO 407 Hydrobiology 3 E 30 45
BIO 413 Field Course II 3 R - -
BIO 414 Human Genetics and Genomics 3 R 45 -
BIO 415 Project 6 C - -
MCB 404 Advanced Food Microbiology T3 E 30 45
MCB 423 Industrial Microbiology 3 E 30 45
MCB 425 Environmental Microbiology 3 E 30 45
MCB 482 Virology and Tissue CulFture 3 E 30 45
ZOO 412 Principles of Parasitology 4 E 45 45
BIO 101: General Biology I (3 Units: LH 45)
BIO 102: General Biology II (3 Units: LH 45)
BIO 107: General Biology Practical I (1 Unit; PH 45)
Laboratory experiments designed to illustrate the topics covered in BIO 101
BIO 108: General Biology Practical II (1 Unit; PH 45)
Experiments designed to emphasise the practical aspects of topics of course BIO 102

========= Page 45 =========
BIO 203: General Physiology I (2 Units: LH 30)
BIO 204: Biological Techniques (2 Units: LH 15; PH 45)
BIO 205: Introductory Developmental Cell Biology (3 Units: LH 30; PH 45)
BIO 299: Industrial Attachment I (3 Units)
BIO 301: Genetics II (3 Units: LH 30; PH 45)
from basic principles. Gene interaction. Pre- requisite -BIO 201.
BIO 302: Field Course I (1 Unit; PH 45)
BIO 303: General Cytology (3 Units: LH 30; PH 45)
BIO 304: General Ecology (3 Units: LH 30; PH 45)
Pre-requisite -BIO 202.

========= Page 46 =========
BIO 305: Molecular Biology I (3 Units: LH 45)
Pre-requisite -BIO 205.
BIO 306: General Physiology II (3 Units: LH 30; PH 45)
aspect of crop yield. Prerequisite -BIO 203.
BIO 308: Evolution (2 Units: LH 30)
BIO 309: Introductory Nematology (2 Units: LH 30)
BIO 399: Industrial Field Experience/Attachment for 12 Weeks (3 Units)
BIO 401: Population Genetics (3 Units: LH 45)
BIO 402: Cytogenetics of Plants (3 Units: LH 30; PH 45)
Pre-requisite -BIO 205
BIO 403: Soil Ecology (3 Units: LH 45)
BIO 404: Systematic Biology (3 Units: LH 45)

========= Page 47 =========
BIO 405: Developmental Biology (3 Units: LH 30; PH 45)
BIO 406: Marine Biology (3 Units: LH 30; PH 45)
BIO 407: Hydrobiology (3 Units: LH 30; PH 45)
BIO 413: Field Course II (3 Units)
BIO 414: Human Genetics and Genomics (3 Units: LH 45)
BIO 415: Project (6 Units: PH 270)

========= Page 48 =========

========= Page 49 =========
BIO 101 General Biology I 3 C 45 -
BIO 102 General Biology II 3 C 45 -
BIO 107 General Biology Practical I 1 C - 45
BIO 108 General Biology Practical II 1 C - 45
CHM 101 General Chemistry I 3 R 45 -
CHM 102 General Chemistry II F3 R 45 -
CHM 107 General Chemistry Practical I 1 R - 45
CHM 108 General Chemistry Practical II 1 R - 45
CSC 101 Introduction toA Computer Science 3 R 30 45
GST 111 Communication in English I 2 C 30 -
GST 112 Logic, Philosophy & Human Existence 2 E 30 -
GST 113 NigRerian Peoples and Culture 2 R 30 -
GST 121 Use of Library, Study Skills & ICT 2 C 30 -
MTH 101 Elementary Mathematics I 3 R 45 -
MTH 102 Elementary Mathematics II 3 R 45 -
PHY 101 General Physics I 3 R 45 -
PHY 102 General Physics II 3 R 45 -
PHY 107 General Physics Practical I 1 R - 45
PHY 108 General Physics Practical II 1 R - 45
BCH 201 General Biochemistry I 3 R 45 -
BIO 201 Genetics I 2 C 30 -
BIO 204 Biological Techniques 2 C 15 45
BTG 202 Introduction to Biotechnology 3 C 45 -
BTG 203 Principles of Plant Biotechnology 3 R 30 45
BTG 299 Industrial Attachment I (12 weeks) 3 C - -
CHM 211 Organic Chemistry I 3 R 30 45
CHM 213 Analytical Chemistry I 3 R 30 45
GST 122 Communication in English II 2 C 30 -

========= Page 50 =========
GST 125 Contemporary Health Issues 2 R 30 -
GST 211 Environment and Sustainable 2 R 30 -
GST 223 Introduction to Entrepreneurship 2 R 30 -
MCB 221 General Microbiology 3 R 30 45
MTH 103 Elementary Mathematics III 3 R 45 -
STA 201 Statistics for Agriculture & Biological 4 R 60 -
BCH 202 General Biochemistry II 3 R 45 -
BCH 311 General Biochemistry Practical 2 R - 90
BTG 301 Molecular Genetics 3 C 45 -
BTG 302 Molecular Genetics Laboratory 2 C - 90
BTG 304 Molecular Cell Biology 3 C 45 -
BTG 399 Industrial Attachment II (12 Weeks) 3 C - -
GST 222 Peace Studies & Conflict Resolution 2 R 30 -
GST 224 Leadership Skills 2 R 30 -
GST 311 Entrepreneurship 2 R 30 -
BTG 401 Biotechnology Seminar 1 C
BTG 403 Methods in recombinant DNA 4 C 45 45
BTG 404 Industrial Biotechnology 3 C 45 -
BTG 405 Nucleotide sequence analysis 3 C 45 -
BTG 406 Metabolic Engineering 3 C 45 -
BTG 407 Research Project in Biotechnology 6 C - 270
BTG 416 Bioresources Management 3 R 45 -
BTG 418 Biosafety issues 1 R 15 -
BTG 420 Intellectual Property Rights & Bioethics 1 R 15 -

In [19]:
data = []
with pdfplumber.open("Sciences_BMAS.pdf") as pdf:
    for i in range(32, 34):
        text = pdf.pages[i].extract_text()
        lines = text.split('\n')

        for line in lines:
            match = re.match(r'^([A-Z]{3,4} ?\d{3})\s+(.+?)\s+(\d+)\s+([RCE])\s+(-|\d+)\s+(-|\d+)?$', line.strip())
            if match:
                course_code, title, credit, status, lecture, practical = match.groups()
                data.append({
                    "Course Code": course_code,
                    "Course Title": title,
                    "Credit Unit": int(credit),
                    "Status": status,
                    "Lecture Hours": None if lecture == "-" else int(lecture),
                    "Practical Hours": None if not practical or practical == "-" else int(practical)
                })
df = pd.DataFrame(data)
print(df.head())
df.to_csv("nuc_course_structure.csv", index=False)

  Course Code                  Course Title  Credit Unit Status  \
0     MTH 102     Elementary Mathematics II            3      R
1     PHY 101             General Physics I            3      R
2     PHY 102            General Physics II            3      R
3     PHY 107   General Physics Practical I            1      R
4     PHY 108  General Physics Practical II            1      R

   Lecture Hours  Practical Hours
0           45.0              NaN
1           45.0              NaN
2           45.0              NaN
3            NaN             45.0
4            NaN             45.0